# AUTOMATICALLY GENERATED
# DO NOT EDIT THIS FILE DIRECTLY. Edit /Dockerfile.erb and run /update instead.

FROM alpine

RUN apk add --no-cache \
      ca-certificates \
      wget \
      curl \
      gcc \
      libc-dev \
      make \
      libressl-dev \
      git \
      coreutils \
      gnupg \
      unzip \
      moreutils \
      linux-headers \
      openssl \
#      luajit-dev \
#      lua5.1-dev \
      lua5.3-dev \
#      lua-turbo \
      sudo \
    && rm -rf /tmp/* \
    && mkdir /usr/local/include \
    && export LUA_INCDIR=/usr/include/lua5.3  \
    && cd /tmp  \ 
    && wget https://luarocks.org/releases/luarocks-3.8.0.tar.gz \
    && tar zxpf luarocks-3.8.0.tar.gz \
    && cd luarocks-3.8.0  \
    && ./configure --with-lua-include=/usr/include/lua5.3 \
    && make \
    && sudo make install \
    && cd ..  \
    && rm -rf /tmp/* \
    && sudo luarocks --version \
#    && sudo luarocks install turbo \
    && sudo luarocks install luasocket \
    && sudo luarocks install luafilesystem \    
#    && sudo luarocks install process \
    && sudo luarocks install coxpcall \
    && sudo luarocks install binaryheap \
    && sudo luarocks install Copas \
    && sudo luarocks install CopasTimer \
    && sudo luarocks install tango-copas \
    && sudo luarocks install luasec \
    && sudo luarocks install mobdebug \
    && apk del gcc make curl wget libc-dev moreutils coreutils git \
    && lua5.3 -v
    
ENV LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/usr/local/lib"

WORKDIR /develop/
RUN mkdir db
EXPOSE 8080/tcp 8888/tcp
ENV HC2DOCKER=TRUE


#COPY server .
#COPY log .
#COPY cli .
#COPY images/. images/.
#COPY dtemplates/. dtemplates/. 
#COPY html/. html/.
#COPY HC2proxy.lua .
#COPY HC2_api.lua .

ENTRYPOINT ["luajit"]
